apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
    release: "3"
spec:
  type: ClusterIP
  ports:
    - name: hello-world
      port: 80
      protocol: TCP
      targetPort: deployment-port
  selector:
    app: hello-world
    release: "3"
